### ISSUE TITLE
회원가입 API error-code 추가 건의

### ISSUE THREAD

**Issue by regular1020** [namsic/harmony#6]
현재 API에서는 ID의 길이에 대한 제한을 두고 있고, ID 길이 제한이 넘어갈 경우에 대한 error-code를 정의하고 있지 않습니다.
지난 회의의 결정에 따라 ID의 형식에 대한 체크도 서버에서 진행하는 것으로 확정된 만큼 현재 있는 error-code에 ID 길이 제한 혹은 형식 오류에 따른 error-code를 추가하여야 할 것 같습니다.

이에 서버에서 ID 체크할 시 길이 문제와 형식 문제를 구분할 수 있는지, 없는지에 따라 달라질 것으로 생각됩니다.

1. 길이로 인한 거부, 형식 불일치를 정규표현식으로 한번에 검사하기에 구분 불가능 할 경우

|에러 코드|설명|
|------|---|
|03|ID 길이, 형식 미일치|

2. 길이로 인한 거부와 형식 미일치를 구분할 수 있는 경우

|에러 코드|설명|
|------|---|
|03|ID 길이 제한 초과|
|04|ID 형식 오류|

어떤 쪽이 구현하기에 적절한지 의견 주시기 바랍니다.

**Comment by namsic** [comment]
길이 또한 형식의 한 종류로 볼 수 있으므로 하나의 정규식 사용하고, 에러 코드도 하나만 사용하는 것이 좋겠습니다.

@regular1020 
서버와는 별개로 현재 웹 회원가입 페이지를 보면 사용자 입력에 따라
실시간으로 길이제한에 대한 피드백을 제공하고 있는데, 가능하다면 이러한 형태의 구현 고려 바랍니다.

**Comment by B2SIC** [comment]
구현 관점에서 살펴보면 위 내용은 조금 더 디테일한 부분까지 다뤄야 할 것 같아 별도로 Issue를 추가하려다가 관련 내용이 여기에 열려있어 본문 내용에 대한 의견과 함께 작성하겠습니다.

### Issue 관련 내용
우선 길이 제약 위배와 형식 미일치는 구분이 가능합니다.

다만 namsic님이 남긴 의견처럼 길이 또는 형식 등 입력 값에 대한 Validation은 각각의 필드 별로 서로 상이하고 종류도 많아질 수 있어 하나로 묶는 것이 좋다고 생각합니다.

따라서 제 의견은 **"구분은 가능하나 1번과 같이 구성하는 것이 좋아보인다."** 입니다.

### 공통 Error Code 분리
API 종류와 관계 없이 공통적으로 발생할 수 있는 에러가 존재합니다.

구현 중 발견한 Exception 2가지를 예시로 들어보면,
* 입력 값의 오류 (필수 필드 미포함, 필드 별 제약 조건 또는 형식 위배)
* 잘못된 요청 데이터 형식
  * Request Body에 잘못된 타입의 값이 들어오는 경우 (ex: Not JSON)

이와 같이 공통적으로 발생할 수 있는 에러는 Method 코드를 제외하고 명확하게 구분할 수 있도록 음수 -1, -2 등을 사용해서 구분하는 것은 어떤지에 대한 의견을 듣고 싶습니다.

#### 예시: [POST] /member
Request Body
```
{
  "user_id": "test_id"
}
```
Response Body
```
{
  "message": "필수 값이 존재하지 않거나 잘못된 값이 입력되었습니다.",
  "errorCode": -1
}
```
Request Body
```
"user_id": "test_id2"
```
```
{
  "message": "잘못된 요청 데이터 형식입니다.",
  "errorCode": -2
}
```

이와 같이 처리 할 경우 동일한 Exception에 대해서는 Error Code까지 동일하게 처리가 가능하기 때문에 좀 더 직관적입니다.

다만 이렇게 할 경우 Spring이 제공하는 @Valid에 의해 필수 필드가 들어오지 않았을 때와 설정한 제약 조건을 위배한 Exception이 동일하기 때문에 두 경우 중 어떤 문제로 Exception이 발생했는지 안내해줄 수 없다는 문제가 있습니다.
추가로 어떤 필드에서 발생한 문제인지도 알 수 없습니다.

하지만 API 문서에는 해당 부분(Required Data + 필드별 제약 조건)이 명시될 예정이기 때문에 이 부분은 사용자에게 위임하는 것이 좋지 않을까 생각합니다.

관련 의견 주시면 감사하겠습니다.

**Comment by namsic** [comment]
- B2SIC/harmony-server#5 
위 PR에서 동일 ErrorCode(0) 사용하도록 구현되었으므로 close 합니다.
