### ISSUE TITLE
[API] 공통 Error Code 분리

### ISSUE THREAD

**Issue by B2SIC** [namsic/harmony#7]
### 공통 Error Code 분리
API 종류와 관계 없이 공통적으로 발생할 수 있는 에러가 존재합니다.

구현 중 발견한 Exception 2가지를 예시로 들어보면,
* 입력 값의 오류 (필수 필드 미포함, 필드 별 제약 조건 또는 형식 위배)
* 잘못된 요청 데이터 형식
  * Request Body에 잘못된 타입의 값이 들어오는 경우 (ex: Not JSON)

이와 같이 공통적으로 발생할 수 있는 에러는 Method 코드를 제외하고 명확하게 구분할 수 있도록 음수 -1, -2 등을 사용해서 구분하는 것은 어떤지에 대한 의견을 듣고 싶습니다.

#### 예시: [POST] /member
Request Body
```
{
  "user_id": "test_id"
}
```
Response Body
```
{
  "message": "필수 값이 존재하지 않거나 잘못된 값이 입력되었습니다.",
  "errorCode": -1
}
```
Request Body
```
"user_id": "test_id2"
```
```
{
  "message": "잘못된 요청 데이터 형식입니다.",
  "errorCode": -2
}
```

이와 같이 처리 할 경우 동일한 Exception에 대해서는 Error Code까지 동일하게 처리가 가능하기 때문에 좀 더 직관적입니다.

이렇게 할 경우 Spring이 제공하는 `@Valid`에 의해 필수 필드가 들어오지 않았을 때와 설정한 제약 조건을 위배한 Exception이 동일하기 때문에 두 경우 중 어떤 문제로 Exception이 발생했는지, 어떤 필드에서 발생한 Exception인지 까지 안내해줄 필요가 있을지에 대한 여부를 결정해야 합니다.

* 예시처럼 "필수 값이 존재하지 않거나 잘못된 값이 입력되었습니다." 라고 작성하는 방법
* 발생한 오류와 필드를 Message에 모두 담아서 보내주는 방법
  * Validation에 실패한 모든 내역을 담고 있기 때문에 Message가 길어질 우려가 있습니다.

하지만 API 문서에는 해당 부분(Required Data + 필드별 제약 조건)이 명시될 예정이기 때문에 이 부분은 사용자에게 위임하는 것이 좋지 않을까 생각합니다.

관련 의견 주시면 감사하겠습니다.

**Comment by namsic** [comment]
error code가 단순히 요청 이후 클라이언트 동작을 결정하는 용도로만 사용되는 경우
method code를 완전히 제거해도 문제가 없습니다.
서로 다른 method가 전혀 다른 원인으로 같은 error code를 사용하더라도
클라이언트는 자신이 보낸 요청이 무엇인지 알기 때문에 각각의 요청에 따라 동작을 구분할 수 있습니다.

그럼에도 method code를 사용하는 경우 디버깅에 도움이 됩니다. 예를 들어, 메시지 전송 버튼을 누를 때
1. 전송 요청
2. 채팅 history를 다시 로드
3. 상대방 읽음 여부 확인

위 3개 동작을 연달아 수행한다고 하면, 문제가 생긴 경우 셋 중 어디에서 발생했는지 확인해야 합니다.
각 메서드마다 -1인 경우 다른 동작을 하도록 구현할 수도 있지만, method code를 사용하는 경우
단순히 error code를 로그로 남기는 것만으로 어디서 문제가 발생했는지 파악할 수 있습니다.

모든 api에서 공통으로 발생하는 예외가 있다면 특정 구역(00~09)을 reserved code로 정해두고
공통 예외가 아닌 경우 다른 code를 사용하도록 하는 것이 어떤지 검토 바랍니다.

**Comment by namsic** [comment]
1, 2, 3은 하나의 api에서 처리하는 것이 아니라 각각 다른 api로 구분되어야 하며,
클라이언트에서 버튼 하나를 눌렀을 때 서버로 3개의 서로 다른 body를 갖는 요청이 전달되는 것입니다.

이 경우 1번은 올바른 json format을 지켜서 보냈지만,
2번은 필수 값을 누락해서 보냈다면 `-1` 응답에 해당하지 않나요?

**Comment by namsic** [comment]
@regular1020 @B2SIC 
추가로 현재 정상 동작의 경우 `"OK"` message를 응답하도록 되어 있는데,
이에 추가로 error code `00`을 이용하는 것은 어떤지 의견이 궁금합니다.
이 경우 `errorCode` 대신 `resultCode`, `responseCode` 등으로 이름 변경을 고려할 필요가 있습니다.

**Comment by B2SIC** [comment]
statusCode를 사용하는건 어떤가요?

성공의 경우 200, 클라이언트 측 오류 400 , 서버 측 오류 500 등..

**Comment by regular1020** [comment]
정상 동작시에 대한 상황을 나타내야 한다면 statusCode를 사용하는 것이 더 좋아 보입니다.
statusCode를 통해 정상적으로 동작 되었는지, 오류가 발생했는지 확인 후 오류가 발생했을 경우에만 해당 오류의 원인을 확인하기 위해서 errorCode를 사용하기 때문에 굳이 성공 시 코드를 추가해야 할 필요는 없어 보입니다.

**Comment by B2SIC** [comment]
statusCode를 사용한다면 다음과 처리한다면 좀 더 편하지 않을까요?

* 정상 동작
  * statusCode: 200
* 에러 발생 상황
  * statusCode: 404 or 400 or 500 .. , errorMsg: "입력 값 오류"

**Comment by namsic** [comment]
> statusCode를 통해 정상적으로 동작 되었는지, 오류가 발생했는지 확인 후 오류가 발생했을 경우에만 해당 오류의 원인을 확인하기 위해서 errorCode를 사용하기 때문에 굳이 성공 시 코드를 추가해야 할 필요는 없어 보입니다.

현재 클라이언트 동작은 아래와 같이 두 번 분기하는 형태일 것으로 생각됩니다.
- statusCode(or `"OK" message` or `errorCode 존재 유무`) 확인
  - 정상인 경우 `동작 1` 수행
  - 아닌 경우 errorCode 확인
    - errorCode 01인 경우 `동작 2` 수행
    - errorCode 02인 경우 `동작 3` 수행

@regular1020 
성공 시 코드가 있는 경우 아래와 같이 간소화할 수 있지 않나요?
- errorCode 확인
  - 00인 경우 `동작 1` 수행
  - 01인 경우 `동작 2` 수행
  - 02인 경우 `동작 3` 수행

**Comment by regular1020** [comment]
확실히 에러코드에 성공 시 코드를 추가한다면 간소화가 가능합니다.
그렇다면 statusCode는 아예 사용하지 않는 건가요?

**Comment by namsic** [comment]
생각을 정리하다 보니, 서버의 응답은 아래와 같은 형태로 구분할 수 있을 것 같습니다.
| index | http status code | error code | 설명 |
| - | - | - | - |
| 1 | 200~299 | ? | 요청한 동작을 성공적으로 수행한 상태 |
| 2 | ? | 있음 | 요청한 동작을 수행하기에 문제가 있는 상태 |
| 3 | 400~599 | 없음 | 예상치 못한 문제가 발생하여 정상 흐름을 벗어난 상태 |

현재 요청 json format이 잘못된 경우 또는 길이 제한을 벗어난 경우 3번 상태인 것으로 알고 있습니다.
(서버에서 생성한 응답이 아닌 spring에 의해 자동 생성된 응답. 문제 원인이 무엇인지 정확히 파악 불가능)

어떠한 형태이든 경우에 따라 status code와 error code를 모두 확인해야 할 필요가 있습니다.
아래 방법 외 다른 방법은 응답에 error code 필드가 있는지 확인하는 과정이 필요할 것 같은데, 좋은 방법이 있으면 의견 바랍니다.
- 1번 상태에 성공 코드 추가 & 2번 상태에 200 status code 적용
(200인 경우 error code 있음 & 200 아닌 경우 에러 코드 없음으로 구분)

**Comment by B2SIC** [comment]
statusCode 하나면 동작 여부를 파악할 수 있다고 생각합니다.

* 요청한 동작을 정상적으로 처리 -> HTTP 200 OK
* 문제 발생 -> HTTP NOT 200 OK
  * 400 ~ 599
  * 발생한 문제에 따라 클라이언트 측 오류 / 서버 측 오류로 구분 + 세부 오류 사항에 따라 Status Code 적용 (권한 문제 등)

이렇게 분기해서 statusCode가 200이라면 정상 요청으로,
200이 아니라면 서버에서 전달하는 errorCode와 Message를 통해 원인을 파악할 수 있도록 구성하면 클라이언트 측에서도 구현하기 편리한 상황이 되지 않을까요?

**Comment by namsic** [comment]
@B2SIC status code가 200이 아닌 상황에서 error code가 없는 상황이 발생할 수 있습니다.
따라서 에러 코드를 400 or 500 status code와 함께 전달하는 경우
- `Not 200 => 에러코드 확인`시 문제가 발생할 수 있고,
- `Not 200 => 에러코드 있는지 검사 => 에러코드 확인`의 형태로 처리해야 하므로
클라이언트의 구현이 편리해지는 것은 아닙니다.

https://sanghaklee.tistory.com/61
위 글을 보니 http status code 및 응답 body 구조를 잘 설계하면 별도의 error code 없이
http status code만으로 핸들링할 수 있을 것 같기도 한데, 이에 대해 의견이 있으면 알려주기 바랍니다.

**Comment by B2SIC** [comment]
b2sic/harmony-server#4
에러 이유에 대해서 명시하는 형태로 Response Body를 구성한 모습입니다.
참고하셔서 원하는 형식이 있다면 예제를 함께 첨부해서 피드백 주시면 감사하겠습니다.
